name = "OpenSCI"
uuid = "b1f315a8-0795-4a8a-b69d-273f1faf0bf4"
authors = ["Nick Mayhall"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
